# Generated by Django 3.0.5 on 2020-04-19 01:29

from django.core.management import call_command
from django.db import migrations

APP_NAME = __package__.split(".")[0]


def import_states(apps, schema_editor):
    call_command("loaddata", "states", verbosity=2)


class Migration(migrations.Migration):

    dependencies = [
        ("taxtea", "0001_initial"),
    ]

    operations = [migrations.RunPython(import_states, None)]
