# Generated by Django 3.0.5 on 2020-04-24 14:21

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', localflavor.us.models.USStateField(max_length=2)),
                ('collects_saas_tax', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zipcodes', to='tax.State')),
            ],
        ),
    ]
