name: CI



on:
  repository_dispatch:
    types: [lint-pass]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      
      - name: "[Python] Set up ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "[Python] Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: "[Python] Check for vulnerable packages"
        run: |
          safety check
      - name: "[Django] Run Tests"
        run: python manage.py test