name: Lint

on:
  push:
    branches: [master, dev]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
      - name: "[Repo] Check out Git repository"
        uses: actions/checkout@v2
      # isort, Black, & Poetry
      - name: "[Python] Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "[Python] Install Poetry"
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: "[Python] Update Req.txts & Install"
        run: |
          poetry export -f requirements.txt > requirements.txt
          poetry export --dev -f requirements.txt > requirements-dev.txt
          pip install -r requirements-dev.txt
      - name: "[Python] isort & Black Linting"
        run: |
          poetry run isort .
          poetry run black ./lowercase
      
      # Commit changes
      - name: "[Git] Commit linting changes"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-formatting" -a || echo "Formatting is good, nothing to update"
      - name: "[Git] Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}